services:
  postgres:
    container_name: database
    image: postgres
    restart: always
    env_file:
      - ./.env
    hostname: postgres_database
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    links:
      - "postgres:database"
    container_name: adminer
    image: adminer
    restart: always
    environment:
      host: localhost
    ports:
      - 8080:8080

  app:
    depends_on:
      - postgres
    links:
      - "postgres:database"
    container_name: app
    restart: always
    build: .
    env_file:
      - ./.env
    ports:
      - 5000:5000

volumes:
  db-data:
